# Generated by Django 4.0.3 on 2022-04-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deepwork',
            options={'ordering': ['project']},
        ),
        migrations.RemoveField(
            model_name='deepwork',
            name='tasks',
        ),
        migrations.AddField(
            model_name='deepwork',
            name='tasks',
            field=models.ManyToManyField(to='backend.arr'),
        ),
    ]
