# Generated by Django 4.0.3 on 2022-04-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_arr_alter_deepwork_options_remove_deepwork_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepwork',
            name='tasks',
        ),
        migrations.AddField(
            model_name='arr',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arr',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.deepwork'),
            preserve_default=False,
        ),
    ]
