# Generated by Django 4.0.3 on 2022-04-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_deepwork_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepwork',
            name='open',
        ),
    ]
