# Generated by Django 4.0.1 on 2022-04-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_deepwork_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.deepwork')),
            ],
        ),
        migrations.AlterField(
            model_name='arr',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.section'),
        ),
    ]
